mutation UpdateUser($id: ID!, $name: String, $birthDate: DateTime) {
  updateUser(
    id: $id
    name: $name
    birthDate: $birthDate
    snapshot: "update-user-mutation"
    delay: 1000
  ) {
    id
    name
    birthDate
  }
}
