// this file is generated by houdini — do not edit
import { jsx as _jsx, jsxs as _jsxs, Fragment } from 'react/jsx-runtime'
import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
import type { JSX as ReactJSX } from 'react/jsx-runtime'

// These imports only resolve after codegen writes the manifest into .houdini/.
// In the source package (template context) the path is absent — hence the suppression.
// @ts-ignore
import type rawManifest from './plugins/houdini-react/runtime/manifest.js'
// @ts-ignore
import type { RouteScalars } from './plugins/houdini-react/runtime/manifest.js'

type _Pages = (typeof rawManifest)['pages']
type _TSType<T extends string> = T extends keyof RouteScalars
	? RouteScalars[T]
	: T extends 'number'
		? number
		: T extends 'boolean'
			? boolean
			: string
type _Param = { readonly name: string; readonly type: string; readonly optional: boolean }
type _ParamObj<Ps extends readonly _Param[]> = {
	[P in Ps[number] as P['name']]: P['optional'] extends true
		? _TSType<P['type']> | undefined
		: _TSType<P['type']>
}
type _ToAnchorProps<P> = P extends {
	readonly url: infer U extends string
	readonly params: readonly []
}
	? { href: U; params?: never }
	: P extends {
				readonly url: infer U extends string
				readonly params: infer Ps extends readonly _Param[]
			}
		? { href: U; params: _ParamObj<Ps> }
		: never

type RouteAnchorProps =
	| { href?: string & {}; params?: Record<string, string | number | boolean> }
	| _ToAnchorProps<_Pages[keyof _Pages]>

type AnchorProps = Omit<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, 'href'> & RouteAnchorProps

export declare namespace JSX {
	type Element = ReactJSX.Element
	type ElementType = ReactJSX.ElementType
	type ElementClass = ReactJSX.ElementClass
	type ElementAttributesProperty = ReactJSX.ElementAttributesProperty
	type ElementChildrenAttribute = ReactJSX.ElementChildrenAttribute
	type LibraryManagedAttributes<C, P> = ReactJSX.LibraryManagedAttributes<C, P>
	type IntrinsicAttributes = ReactJSX.IntrinsicAttributes
	type IntrinsicClassAttributes<T> = ReactJSX.IntrinsicClassAttributes<T>
	type IntrinsicElements = Omit<ReactJSX.IntrinsicElements, 'a'> & {
		a: AnchorProps
	}
}

function resolveHref(href: string, params: Record<string, string | number | boolean>): string {
	return href.replace(/\[([^\]]+)\]/g, (_, key: string) => String(params[key] ?? key))
}

export function jsx(type: any, props: any, key?: any): any {
	if (type === 'a' && props?.params != null) {
		const { params, href, ...rest } = props
		return _jsx('a', { ...rest, href: resolveHref(href, params) }, key)
	}
	return _jsx(type, props, key)
}

export function jsxs(type: any, props: any, key?: any): any {
	if (type === 'a' && props?.params != null) {
		const { params, href, ...rest } = props
		return _jsxs('a', { ...rest, href: resolveHref(href, params) }, key)
	}
	return _jsxs(type, props, key)
}

export { Fragment }
