// this file is generated by houdini — do not edit
import { jsxDEV as _jsxDEV, Fragment } from 'react/jsx-dev-runtime'
import type { JSX as ReactJSX } from 'react/jsx-runtime'
import type { AnchorHTMLAttributes } from 'react'

type RouteAnchorProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & (
// HOUDINI_ROUTE_UNION
)

export declare namespace JSX {
    type Element = ReactJSX.Element
    type ElementType = ReactJSX.ElementType
    type ElementClass = ReactJSX.ElementClass
    type ElementAttributesProperty = ReactJSX.ElementAttributesProperty
    type ElementChildrenAttribute = ReactJSX.ElementChildrenAttribute
    type LibraryManagedAttributes<C, P> = ReactJSX.LibraryManagedAttributes<C, P>
    type IntrinsicAttributes = ReactJSX.IntrinsicAttributes
    type IntrinsicClassAttributes<T> = ReactJSX.IntrinsicClassAttributes<T>
    type IntrinsicElements = Omit<ReactJSX.IntrinsicElements, 'a'> & {
        a: RouteAnchorProps
    }
}

function resolveHref(href: string, params: Record<string, string>): string {
    return href.replace(/\[([^\]]+)\]/g, (_, key: string) => params[key] ?? key)
}

export function jsxDEV(type: any, props: any, key?: any, isStaticChildren?: boolean, source?: any, self?: any): any {
    if (type === 'a' && props?.params != null) {
        const { params, href, ...rest } = props
        return _jsxDEV('a', { ...rest, href: resolveHref(href, params) }, key, isStaticChildren, source, self)
    }
    return _jsxDEV(type, props, key, isStaticChildren, source, self)
}

export { Fragment }
