// this file is generated by houdini — do not edit
import { jsxDEV as _jsxDEV, Fragment } from 'react/jsx-dev-runtime'
import { resolveHref } from './resolve-href.js'
export type { JSX } from './jsx-types.js'

export function jsxDEV(
	type: any,
	props: any,
	key?: any,
	isStaticChildren?: boolean,
	source?: any,
	self?: any
): any {
	if (type !== 'a') return _jsxDEV(type, props, key, isStaticChildren ?? false, source, self)
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	const { params, suppressHrefTypeCheck: _s, href, ...rest } = props ?? {}
	if (params != null) {
		return _jsxDEV(
			'a',
			{ ...rest, href: resolveHref(href, params) },
			key,
			isStaticChildren ?? false,
			source,
			self
		)
	}
	return _jsxDEV('a', { href, ...rest }, key, isStaticChildren ?? false, source, self)
}

export { Fragment }
