// this file is generated by houdini — do not edit
import { jsx as _jsx, jsxs as _jsxs, Fragment } from 'react/jsx-runtime'
import type { JSX as ReactJSX } from 'react/jsx-runtime'
import type { AnchorHTMLAttributes } from 'react'

type RouteAnchorProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & (
// HOUDINI_ROUTE_UNION
)

export declare namespace JSX {
    type Element = ReactJSX.Element
    type ElementType = ReactJSX.ElementType
    type ElementClass = ReactJSX.ElementClass
    type ElementAttributesProperty = ReactJSX.ElementAttributesProperty
    type ElementChildrenAttribute = ReactJSX.ElementChildrenAttribute
    type LibraryManagedAttributes<C, P> = ReactJSX.LibraryManagedAttributes<C, P>
    type IntrinsicAttributes = ReactJSX.IntrinsicAttributes
    type IntrinsicClassAttributes<T> = ReactJSX.IntrinsicClassAttributes<T>
    type IntrinsicElements = Omit<ReactJSX.IntrinsicElements, 'a'> & {
        a: RouteAnchorProps
    }
}

function resolveHref(href: string, params: Record<string, string>): string {
    return href.replace(/\[([^\]]+)\]/g, (_, key: string) => params[key] ?? key)
}

export function jsx(type: any, props: any, key?: any): any {
    if (type === 'a' && props?.params != null) {
        const { params, href, ...rest } = props
        return _jsx('a', { ...rest, href: resolveHref(href, params) }, key)
    }
    return _jsx(type, props, key)
}

export function jsxs(type: any, props: any, key?: any): any {
    if (type === 'a' && props?.params != null) {
        const { params, href, ...rest } = props
        return _jsxs('a', { ...rest, href: resolveHref(href, params) }, key)
    }
    return _jsxs(type, props, key)
}

export { Fragment }
