// this file is generated by houdini — do not edit
// @refresh reset
import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
import { getCurrentConfig } from '$houdini/runtime/config'
import React from 'react'

// @ts-ignore
import manifest from './manifest.js'
import type { RouteHrefs, ExternalHref, ParamsForRoute, SearchForRoute } from './routes.js'

import { buildHref, type RouteHrefInfo } from './resolve-href.js'

// re-exported for custom link wrappers that constrain their own `to` prop
export type { RouteHrefs, ExternalHref }

export type LinkProps<H extends RouteHrefs | ExternalHref = RouteHrefs | ExternalHref> = Omit<
	DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>,
	'href'
> & {
	to: H
	disabled?: boolean
	preload?: boolean | 'data' | 'component' | 'page'
} & ParamsForRoute<H> &
	SearchForRoute<H>

export function Link<H extends RouteHrefs | ExternalHref>({
	to,
	params,
	search,
	disabled,
	preload,
	...rest
}: LinkProps<H>): React.ReactElement {
	// look up the destination route (O(1) via the codegen'd pagesByUrl map) so custom-scalar
	// param/search values can be marshaled into their transport form (e.g. a Date →
	// timestamp) before they hit the URL. External hrefs won't match a page, so marshalers
	// stay empty.
	const m = manifest as any
	const page = m.pages[m.pagesByUrl[to as string]] as RouteHrefInfo | undefined
	const href = disabled
		? undefined
		: buildHref(
				to as string,
				page,
				getCurrentConfig()?.scalars,
				params as Record<string, unknown> | undefined,
				search as Record<string, unknown> | undefined
			)
	return React.createElement('a', { ...rest, href, 'data-houdini-preload': preload })
}
