// this file is generated by houdini — do not edit
// @refresh reset
import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
import React from 'react'

// @ts-ignore
import type rawManifest from './manifest.js'
// @ts-ignore
import type { RouteScalars } from './manifest.js'

import { resolveHref } from './resolve-href.js'

type _Pages = (typeof rawManifest)['pages']
type _TSType<T extends string> = T extends keyof RouteScalars
	? RouteScalars[T]
	: T extends 'Int' | 'Float'
		? number
		: T extends 'ID'
			? string | number
			: T extends 'Boolean'
				? boolean
				: string
type _Param = { readonly name: string; readonly type: string; readonly optional: boolean }
type _ParamObj<Ps extends readonly _Param[]> = {
	[P in Ps[number] as P['optional'] extends true ? P['name'] : never]?: _TSType<P['type']>
} & {
	[P in Ps[number] as P['optional'] extends true ? never : P['name']]: _TSType<P['type']>
}
type _ToRouteProps<P> = P extends {
	readonly url: infer U extends string
	readonly params: readonly []
}
	? { to: U; params?: never }
	: P extends {
				readonly url: infer U extends string
				readonly params: infer Ps extends readonly _Param[]
			}
		? { to: U; params: _ParamObj<Ps> }
		: never

type _ExternalHref =
	| `http://${string}`
	| `https://${string}`
	| `mailto:${string}`
	| `tel:${string}`
	| `blob:${string}`
	| `data:${string}`
	| `//${string}`
	| `#${string}`
	| `./${string}`
	| `../${string}`

// All known app route URL strings — useful as a constraint for custom link wrappers.
export type RouteHrefs = _Pages[keyof _Pages] extends { readonly url: infer U extends string }
	? U
	: never

type _PropsForRoute<H extends string> = [
	Extract<_Pages[keyof _Pages], { readonly url: H }>,
] extends [never]
	? { to: H; params?: never }
	: _ToRouteProps<Extract<_Pages[keyof _Pages], { readonly url: H }>>

type _CheckedProps<H extends string> = Omit<
	DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>,
	'href'
> &
	_PropsForRoute<H>

type _UncheckedProps = Omit<
	DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>,
	'href'
> & {
	suppressTypeCheck: true
	to: string
	params?: Record<string, string | number | boolean>
}

export type LinkProps<H extends string = RouteHrefs | _ExternalHref> =
	| _CheckedProps<H>
	| _UncheckedProps

export function Link<H extends string>({
	to,
	params,
	suppressTypeCheck: _s,
	...rest
}: LinkProps<H> & { suppressTypeCheck?: true }): React.ReactElement {
	const href =
		params != null
			? resolveHref(to as string, params as Record<string, string | number | boolean>)
			: (to as string)
	return React.createElement('a', { ...rest, href })
}
