// this file is generated by houdini — do not edit
// @refresh reset
import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
import React from 'react'

// @ts-ignore
import type rawManifest from './manifest.js'
// @ts-ignore
import type { RouteScalars } from './manifest.js'

import { resolveHref } from './resolve-href.js'

type _Pages = (typeof rawManifest)['pages']
type _TSType<T extends string> = T extends keyof RouteScalars
	? RouteScalars[T]
	: T extends 'Int' | 'Float'
		? number
		: T extends 'ID'
			? string | number
			: T extends 'Boolean'
				? boolean
				: string
type _Param = { readonly name: string; readonly type: string; readonly optional: boolean }
type _ParamObj<Ps extends readonly _Param[]> = {
	[P in Ps[number] as P['optional'] extends true ? P['name'] : never]?: _TSType<P['type']>
} & {
	[P in Ps[number] as P['optional'] extends true ? never : P['name']]: _TSType<P['type']>
}

type _ExternalHref =
	| `http://${string}`
	| `https://${string}`
	| `mailto:${string}`
	| `tel:${string}`
	| `blob:${string}`
	| `data:${string}`
	| `//${string}`
	| `#${string}`
	| `./${string}`
	| `../${string}`

// All known app route URL strings — useful as a constraint for custom link wrappers.
export type RouteHrefs = _Pages[keyof _Pages] extends { readonly url: infer U extends string }
	? U
	: never

// Separate 'to' from 'params' so TypeScript evaluates them independently:
// - 'to' completions show all routes (including parameterized) because 'to' itself is always valid
// - 'params' is a separate intersection that errors when required but absent
type _PageForRoute<H extends string> = Extract<_Pages[keyof _Pages], { readonly url: H }>
type _ParamsForRoute<H extends string> = [_PageForRoute<H>] extends [never]
	? { params?: never }
	: _PageForRoute<H> extends { readonly params: readonly [] }
		? { params?: never }
		: _PageForRoute<H> extends { readonly params: infer Ps extends readonly _Param[] }
			? { params: _ParamObj<Ps> }
			: { params?: never }

export type LinkProps<H extends RouteHrefs | _ExternalHref = RouteHrefs | _ExternalHref> = Omit<
	DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>,
	'href'
> & { to: H } & _ParamsForRoute<H>

export function Link<H extends RouteHrefs | _ExternalHref>({ to, params, ...rest }: LinkProps<H>): React.ReactElement {
	const href =
		params != null
			? resolveHref(to as string, params as Record<string, string | number | boolean>)
			: (to as string)
	return React.createElement('a', { ...rest, href })
}
