projects:
    default:
        # 👇 For vscode-graphql and intellisense
        schema:
            - e2e/api/*.graphql
            - e2e/$houdini/graphql/schema.graphql
        documents:
            - e2e/src/**/*.gql
            - e2e/$houdini/graphql/documents.gql
