projects:
    default:
        # 👇 For vscode-graphql and intellisense
        schema:
            - integration/api/*.graphql
            - integration/$houdini/graphql/schema.graphql
        documents:
            - integration/src/**/*.gql
            - integration/$houdini/graphql/documents.gql
