projects:
    sveltekit:
        # 👇 For vscode-graphql and intellisense
        schema:
            - e2e/_api/*.graphql
            - e2e/sveltekit/$houdini/graphql/schema.graphql
        documents:
            - e2e/sveltekit/src/**/*.gql
            - e2e/sveltekit/$houdini/graphql/documents.gql
