/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialChapterStepRouteImport } from './routes/tutorial.$chapter.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialChapterStepRoute = TutorialChapterStepRouteImport.update({
  id: '/tutorial/$chapter/$step',
  path: '/tutorial/$chapter/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tutorial/$chapter/$step': typeof TutorialChapterStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tutorial/$chapter/$step': typeof TutorialChapterStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tutorial/$chapter/$step': typeof TutorialChapterStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tutorial/$chapter/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tutorial/$chapter/$step'
  id: '__root__' | '/' | '/tutorial/$chapter/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TutorialChapterStepRoute: typeof TutorialChapterStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/$chapter/$step': {
      id: '/tutorial/$chapter/$step'
      path: '/tutorial/$chapter/$step'
      fullPath: '/tutorial/$chapter/$step'
      preLoaderRoute: typeof TutorialChapterStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TutorialChapterStepRoute: TutorialChapterStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
