query Page_User_Friends($userId: ID!, $size: Int) {
  user(id: $userId, snapshot: "Page_User", delay: 1200) {
    id
    friendsConnection(first: $size) {
      edges {
        node {
          id
        }
      }
    }
  }
}
