name: '🐛 Bug report'
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug :pray:.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: To help us, please provide a [stackblitz](https://stackblitz.com/) or [replay.io](https://docs.replay.io/docs/recording-bug-reports-80c37d7d6753485f81497570625d06f0) link showing your bug. _A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is a nice option to get your bug fixed asap ([Why?](https://antfu.me/posts/why-reproductions-are-required))._
      placeholder: 🔗 Reproduction link
