blank_issues_enabled: false
contact_links:
  - name: Have a question?
    url: https://discord.gg/Gd8vfvxpsD
    about: Not sure about something? need help from the community? have a question to our team? please ask and answer questions here.
