query DescriptionPage {
  monkey(id: "1") {
    hasBanana
    oldHasBanana
  }

  userResult(id: "1", snapshot: "test", forceMessage: false) {
    __typename
    ... on User {
      enumValue
    }
  }
}
