directive @cacheControl(
	maxAge: Int
	scope: CacheControlScope
) on FIELD_DEFINITION | INTERFACE | OBJECT

scalar DateTime

input AddItemInput {
	text: String!
}

type AddItemOutput {
	error: Error
	item: TodoItem
}

enum CacheControlScope {
	PRIVATE
	PUBLIC
}

type DeleteIemOutput {
	error: Error
	itemID: ID
}

type Error {
	code: String!
	message: String!
}

type ItemUpdate {
	item: TodoItem!
}

type Mutation {
	addItem(input: AddItemInput!): AddItemOutput!
	checkItem(item: ID!): UpdateItemOutput!
	deleteItem(item: ID!): DeleteIemOutput!
	uncheckItem(item: ID!): UpdateItemOutput!
}

type Query {
	items(first: Int, after: String, completed: Boolean): TodoItemConnection!
}

type Subscription {
	itemUpdate(id: ID!): ItemUpdate!
	newItem: ItemUpdate!
}

type TodoItem {
	completed: Boolean!
	id: ID!
	text: String!
	createdAt: DateTime!
}

type UpdateItemOutput {
	error: Error
	item: TodoItem
}

type PageInfo {
	startCursor: String!
	endCursor: String!
	hasNextPage: Boolean!
	hasPreviousPage: Boolean!
}

type TodoItemConnection {
	totalCount: Int!
	pageInfo: PageInfo!
	edges: [TodoItemEdge!]!
}

type TodoItemEdge {
	cursor: String
	node: TodoItem
}

"""
The `Upload` scalar type represents a file upload.
"""
scalar Upload
