projects:
    default:
        schema:
            - ./$houdini/graphql/schema.graphql
        documents:
            - '**/*.gql'
            - '**/*.tsx'
            - ./$houdini/graphql/documents.gql
