name: Canary Release

# on every commit to main, we want to publish a snapshot release:
# for more info: https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md
on:
    push:
        branches:
            - next
            - svelte-5

env:
    CI: true
jobs:
    publish:
        name: Publish Canary Version
        runs-on: ubuntu-22.04
        permissions:
            id-token: write
        steps:
            - name: Checkout source
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
                registry-url: 'https://registry.npmjs.org'
                always-auth: true

            - name: Update npm CLI
              run: npm install -g npm@latest

            - uses: pnpm/action-setup@v2.0.1
              name: Install pnpm
              id: pnpm-install
              with:
                version: 9

            - name: Install dependencies
              run: pnpm install

            - name: Set Git Identity
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Apply and publish the snapshot release
              run: |
                  pnpm changeset version --snapshot
                  pnpm run build
                  pnpm changeset publish --no-git-tag --snapshot --tag canary
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
