name: Publish Release
on: workflow_dispatch

env:
    CI: true
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Attach Head
              run: |
                  git checkout ${{ github.event.pull_request.base.ref }}

            - name: Setup Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14.13
                  registry-url: 'https://npm.pkg.github.com'

            - name: Use HTTPS registry
              run: |
                  npm config set registry https://registry.npmjs.org/

            - name: Set Git Identity
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install and Build
              run: |
                  yarn install --froze-lockfile
                  yarn build

            - name: Create Release Pull Request
              uses: changesets/action@master
              with:
                  publish: yarn release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
